import numpy as np

π = np.pi
τ = 2 * π
P5 = "AATGATACGGCGACCACCGAGATCTACAC"
TRUSEQ1 = "ACACTCTTTCCCTACACGACGCTCTTCCGATCT"
P7 = "CAAGCAGAAGACGGCATACGAGAT"
NEXTERA2 = "GTCTCGTGGGCTCGG"
SMALLRNA = "GTGACTGGAGTTCCTTGGCACCCGAGAATTCCA"
